---
- hosts: localhost
  gather_facts: no
  
  vars_prompt:
  - name: target_host
    prompt: please enter the target host IP
    private: no
  - name: username
    prompt: "Enter username"
    private: no
  - name: password
    prompt: "Enter password"
    private: yes

  tasks:
    - add_host:
        name: "{{target_host}}"
        groups: dynamically_created_hosts
        ansible_user: "{{username}}"
        ansible_password: "{{password}}"
    
 
- hosts: dynamically_created_hosts
  gather_facts: no
  connection: local
  tasks:
    - name: run show verstion
      ios_command:
        commands: show ip ssh | in size
        
      register: show_ver
    - debug: var=show_ver.stdout_lines