---

- set_fact: 
    bitsize: "{{ print_output.stdout | join('') | regex_findall(qry) }}"
        
  vars: 
    qry: '\d{4}'
    
- debug:
    var: bitsize
    
- assert:
    that:
      - "bitsize >= 1024"



